esphome:
  name: current

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

######################################

packages:
  wifi:     !include common/wifi.yaml
  diagnostic:     !include common/diagnostic.yaml

sensor:
  - platform: adc
    pin: A0
    id: adc_sensor
    
  - platform: ct_clamp
    sensor: adc_sensor
    id: current_clean
    name: "Measured Current"
    update_interval: 10s
    filters:
      - calibrate_linear:
          - 0 -> 0
          - 0.18 -> 0.44

  - platform: template
    name: "Measured Watts"
    update_interval: 10s
    lambda: return (id(current_clean).state * 120);
    unit_of_measurement: W